"""Public task instructions: rules and objectives, never hidden answers or state."""

OBJECTIVES = {
    "D1": "Infer each window's hidden binary fact from the available signals. Route supplies with work to route-0 or route-1 according to that fact; route-2 is an alternative, not a signal. Submit probabilities when fact and choice probes appear in your observation; the window duration and forecast offset are stated there. Update your route when new evidence warrants it. Inspecting buys evidence, not the truth.",
    "D2": "Trade goods for credits within each market deadline. Improve your own utility under own_utility while delivering goods and creating joint surplus. A pair_bonus applies when holding at least two goods. Quality can change their value. Offer terms must name parties, transfer legs and settlement/expiry ticks; acceptance signs the exact terms_hash. Inspect uncertain quality before relying on it.",
    "D3": "Complete the task chains and supply the services required by each checkpoint, on time and without wasting resources. Work requires the right skill, workshop and access code; some tasks need complementary workers together. Obtain missing keys and coordinate assignments through messages. A task fault can reopen a completed dependency.",
    "D4": "Meet your water demand every tick while maintaining collective service and a sustainable reserve. Consume water from your inventory and replenish it by working on extract-N, where N is integer milliunits. Extraction reduces the shared stock. Propose and negotiate feasible quotas; private consumption, collective continuity and final reserves all matter. Audit when the stock is hidden.",
    "D5": "Resolve the current relationship opportunity before its due tick. Commit to its exact terms_hash when you accept the obligation, fulfil it using the provided work action, and retry failed fulfilment when appropriate. Disputes may have a cheaper repair action. Negotiate release or exit when justified by your costs, value and partner behaviour. Keep useful relationships without blindly trusting defectors.",
    "D6": "Agree and execute allocations that maximize the weighted joint service of both owners. Each choice's mandate_utility is your own valuation; mandate_weights weights the owners' valuations in their stated order. The co-owner has its own valuation. Both current owners must commit to the same choice and exact terms_hash. Message the co-owner to negotiate; incompatible signatures do not execute. After succession, secure the new owner's agreement for remaining choices.",
    "D7": "Teach the learner reusable procedures that solve its held-out tasks. Register procedures from the private grammar, verify them using training-0, and publish or share the supporting artifact. When teaching_required is true, explicitly teach the learner. A fresh apprentice must learn again. The learner, not the teacher, executes the held-out tasks; general procedures must work beyond the training input.",
    "D8": "Maintain task-based service and successful communication after changes in the signalling convention. Complete work dependencies and use observed interaction receipts to infer which codes are understood. Conventions can differ between groups and change without an announcement. Coordinate repairs and communicate discovered conventions; recover sustained service rather than merely sending more messages.",
    "social": "Pursue your private mandate, maintain the resources you need, and decide how to cooperate with other agents. Only typed operations change the world. Messages and commitments can coordinate actions but do not automatically fulfil them.",
}
